# AppVeyor.com is a Continuous Integration service to build and run tests under Windows
# This .yml file is based on scikit-learn and statsmodels' Appveyor CI setups, adapted for
# use with pmdarima https://ci.appveyor.com/project/tgsmith61591/pmdarima

os: Visual Studio 2015

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script interpreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\build_tools\\appveyor\\run_with_env.cmd"
  PYPI_USERNAME: tgsmith61591.gh
  PYPI_PASSWORD:
    secure: okvMa3VgIXdlnMC48iMefQ==

  matrix:
    - PYTHON_ARCH: "32"
      PYTHON_VERSION: "3.5.1"
      MPL_VERSION: "2.2.3"
      PMDARIMA_MPL_DEBUG: "true"
      PYTHON: "C:\\Python35"

    - PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.5.1"
      MPL_VERSION: "2.2.3"
      PMDARIMA_MPL_DEBUG: "true"
      PYTHON: "C:\\Python35-x64"

    - PYTHON_ARCH: "32"
      PYTHON_VERSION: "3.6.6"
      MPL_VERSION: "2.2.3"
      PMDARIMA_MPL_DEBUG: "true"
      PYTHON: "C:\\Python36"

    - PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.6.6"
      MPL_VERSION: "2.2.3"
      PMDARIMA_MPL_DEBUG: "true"
      PYTHON: "C:\\Python36-x64"

    - PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.7.1"
      MPL_VERSION: "2.2.3"
      PMDARIMA_MPL_DEBUG: "true"
      PYTHON: "C:\\Python37-x64"

# Because we only have a single worker, we don't want to waste precious
# appveyor CI time and make other PRs wait for repeated failures in a failing
# PR. The following option cancels pending jobs in a given PR after the first
# job failure in that specific PR.
matrix:
    fast_finish: true

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds.
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=500).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - "powershell ./build_tools/appveyor/install.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install -U pip"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip --version"

  # 9/25/18 - Use the scikit approach
  # Build the package (and the wheels!)
  - "%CMD_IN_ENV% pip install --timeout=60 -r build_tools/appveyor/requirements.txt"
  - "%CMD_IN_ENV% python setup.py bdist_wheel bdist_wininst"
  - ps: "ls dist"

  # Install the generated wheel file
  - "pip install --pre --no-index --find-links dist/ pmdarima"

# Not a .NET project, we build pmdarima in the install step instead
build: false

test_script:
  # Change to a non-source folder to make sure we run the tests on the
  # installed library
  - mkdir "../empty_folder"
  - "cd ../empty_folder"

  # Test with pytest
  - "pytest --showlocals --durations=20 --pyargs pmdarima"
  - "cd ../pmdarima"

after_test:
  - set PATH=%BK_PATH%

artifacts:
  - path: dist\*

deploy_script:
  - echo "Starting artifact deployment"
  - set PATH=%BK_PATH%
  - ps: If ($env:APPVEYOR_REPO_TAG -eq "true") { Invoke-Expression "twine upload -u tgsmith61591.gh -p $env:PYPI_PASSWORD --skip-existing dist/*" } Else { write-output "Not on a tagged commit, won't deploy to pypi"}
  #- ps: If ($env:APPVEYOR_REPO_BRANCH -eq "develop") { Invoke-Expression "twine upload -u tgsmith61591.gh -p $env:PYPI_PASSWORD --repository-url https://test.pypi.org/legacy/ --skip-existing dist/*" } Else { write-output "Not on a development commit, won't deploy to pypitest"}

cache:
  # Use the appveyor cache to avoid re-downloading large archives such
  # the MKL numpy and scipy wheels mirrored on a rackspace cloud
  # container, speed up the appveyor jobs and reduce bandwidth
  # usage on our rackspace account.
  - '%APPDATA%\pip\Cache'
